name: TWRP Build

on:
  #  release:
  #    types: [published]
  #  push:
  #    branches:
  #      - master
  #    paths:
  #      - '.config'
  #  schedule:
  #    - cron: 0 8 * * 5
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # watch:
  #   types: [started]

env:
  Rec_name: TWRP
  Rec_ver: 3.5.2
  Rec_url: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-11
  device: mojito
  DT_url: https://github.com/boedhack99/rec_mojito -b 11
  DT_path: device/xiaomi/mojito
  BT_url: https://github.com/LineageOS/android_hardware_qcom_bootctrl -b lineage-18.1-caf
  BT_path: hardware/qcom-caf/bootctrl
  target: bootimage
  WorkSpace: WorkSpace
  TZ: Asia/Jakarta
  Author: boedhack99
  Enable_cache: false
  Enable_ccache: true
  Delete_old: false

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: CHECKOUT
        uses: actions/checkout@master

      - name: CLEANUP OLD ENVIRONMENT
        # if: env.Enable_cache == 'true' && !cancelled()
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          docker rmi `docker images -q`
          sudo apt-get remove account-plugin-facebook account-plugin-flickr account-plugin-jabber account-plugin-salut account-plugin-twitter account-plugin-windows-live account-plugin-yahoo aisleriot brltty duplicity empathy empathy-common example-content gnome-accessibility-themes gnome-contacts gnome-mahjongg gnome-mines gnome-orca gnome-screensaver gnome-sudoku gnome-video-effects gnomine landscape-common libreoffice-avmedia-backend-gstreamer libreoffice-base-core libreoffice-calc libreoffice-common libreoffice-core libreoffice-draw libreoffice-gnome libreoffice-gtk libreoffice-impress libreoffice-math libreoffice-ogltrans libreoffice-pdfimport libreoffice-style-galaxy libreoffice-style-human libreoffice-writer libsane libsane-common mcp-account-manager-uoa python3-uno rhythmbox rhythmbox-plugins rhythmbox-plugin-zeitgeist sane-utils shotwell shotwell-common telepathy-gabble telepathy-haze telepathy-idle telepathy-indicator telepathy-logger telepathy-mission-control-5 telepathy-salut totem totem-common totem-plugins printer-driver-brlaser printer-driver-foo2zjs printer-driver-foo2zjs-common printer-driver-m2300w printer-driver-ptouch printer-driver-splix
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*

      - name: SETUP ENVIRONMENT
        run: |
          sudo -E apt-get clean
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install curl libstdc++6 git wget repo rsync aria2
          git config --global user.name "boedhack99"
          git config --global user.email "boedhack@gmail.com"
          git clone https://gitlab.com/OrangeFox/misc/scripts --depth=1 --single-branch
          cd scripts
          sudo -E bash setup/android_build_env.sh
          sudo -E bash setup/install_android_sdk.sh

      - name: SYNC REPO
        run: |
          mkdir WorkSpace
          cd WorkSpace
          repo init -u ${{env.Rec_url}} --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips
          repo sync -j4

      - name: SYNC TREES
        run: |
          cd ${{env.WorkSpace}}
          git clone ${{ env.DT_url }} --depth=1 --single-branch ${{ env.DT_path }}
          cd ${{ env.DT_path }}
          # rm -rf recovery/root/*

      - name: PATCH BOOTCTRL
        run: |
          cd ${{env.WorkSpace}}
          git clone ${{ env.BT_url }} --depth=1 --single-branch ${{ env.BT_path }}

      - name: SHOW TREES
        run: tree -C -d -L 6

      - name: RESTORE CACHE
        uses: actions/cache@v2
        if: env.Enable_cache == 'true' && !cancelled()
        with:
          path: |
            ~/.ccache
            ${{env.WorkSpace}}/out
          key: ${{ runner.os }}-${{env.Rec_name}}-${{env.Rec_ver}}-${{ env.device }} #${{ hashFiles('**/BoardConfig.mk') }}
          restore-keys: |
            ${{ runner.os }}-${{env.Rec_name}}-${{env.Rec_ver}}-${{ env.device }}

      - name: SETUP CCACHE
        uses: alexjurkiewicz/setup-ccache@master
        if: env.Enable_ccache == 'true' && !cancelled()
        with:
          max-size: 5G
          extra-config: |
            keep_comments_cpp = true

      - name: BUILDING ${{env.Rec_name}}
        run: |
          cd ${{env.WorkSpace}}
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          lunch twrp_${{ env.device }}-eng
          repo sync -j4
          mka ${{env.target}}
        shell: bash

      - name: GET INFO
        id: info
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m-%d-%H-%M")"
          echo "::set-output name=OutFolder::"${{env.WorkSpace}}/out/target/product/${{ env.device }}""
        shell: bash

      - name: SHOW OUT TREES
        run: |
          cd ${{steps.info.outputs.OutFolder}}
          sudo zip -r9 ${{env.Rec_name}}_for_${{ env.device }}.zip recovery.img
          tree -C -L 5

      - name: UP FIRMWARE
        uses: actions/upload-artifact@main
        # if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: ${{env.Rec_name}}_for_${{ env.device }}-${{ github.run_id }}
          path: ${{steps.info.outputs.OutFolder}}/*.img

      - name: UP RELEASE
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{steps.info.outputs.OutFolder}}/${{env.Rec_name}}_for_${{ env.device }}.zip
            ${{steps.info.outputs.OutFolder}}/recovery.img
          name: ${{env.Rec_name}}-${{ env.device }}-${{ github.run_id }}
          tag_name: ${{ env.device }}-${{env.Rec_name}}-${{ steps.info.outputs.date }}
          body: |
            ${{env.Rec_name}}-${{env.Rec_ver}} for ${{ env.device }} build at ${{ steps.info.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: CLEAN OLD RELEASE
        uses: dev-drprasad/delete-older-releases@v0.1.0
        if: env.Delete_old == 'true' && !cancelled()
        with:
          keep_latest: 12
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: CLEAN WORKFLOWS
        uses: GitRML/delete-workflow-runs@main
        if: env.Delete_old == 'true' && !cancelled()
        with:
          retain_days: 1
          keep_minimum_runs: 10
